                                        בסייד

Задание 1

In [2]:
import pandas as pd
import numpy as np

In [3]:
horse_df = pd.read_csv('https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/statistics_basics/horse_data.csv',header=None, na_values ='?')

horse_df.drop([2,7,8,9,11,12,13,14,15,16,17,18,19,20,21,23,24,25,26,27], axis=1, inplace=True)
horse_df.columns = ['surgery?', 'Age', 'rectal temperature', 'pulse',
                    'respiratory rate', 'temperature of extremities', 'pain', 'outcome']
horse_df.describe()

,surgery?,Age,rectal temperature,pulse,respiratory rate,temperature of extremities,pain,outcome
count,299.000000,300.000000,240.000000,276.000000,242.000000,244.000000,245.00000,299.000000
mean,1.397993,1.640000,38.167917,71.913043,30.417355,2.348361,2.95102,1.551839
std,0.490305,2.173972,0.732289,28.630557,17.642231,1.045054,1.30794,0.737187
min,1.000000,1.000000,35.400000,30.000000,8.000000,1.000000,1.00000,1.000000
25%,1.000000,1.000000,37.800000,48.000000,18.500000,1.000000,2.00000,1.000000
50%,1.000000,1.000000,38.200000,64.000000,24.500000,3.000000,3.00000,1.000000
75%,2.000000,1.000000,38.500000,88.000000,36.000000,3.000000,4.00000,2.000000
max,2.000000,9.000000,40.800000,184.000000,96.000000,4.000000,5.00000,3.000000

In [8]:
print(f'rectal temperature_mean: {horse_df["rectal temperature"].mean()}')
print(f'rectal temperature_median: {horse_df["rectal temperature"].median()}')
print(f'rectal temperature_mode: {horse_df["rectal temperature"].mode()[0]}')
print(' ')
print(f'pulse_mean: {horse_df["pulse"].mean()}')
print(f'pulse_median: {horse_df["pulse"].median()}')
print(f'pulse_mode: {horse_df["pulse"].mode()[0]}')
print(' ')
print(f'respiratory rate_mean: {horse_df["respiratory rate"].mean()}')
print(f'respiratory rate_median: {horse_df["respiratory rate"].median()}')
print(f'respiratory rate_mode: {horse_df["respiratory rate"].mode()[0]}')
print(' ')
print('Количество пропущенных знацений в %%:')
(horse_df.isna().mean()*100).round(2)

rectal temperature_mean: 38.16791666666667
rectal temperature_median: 38.2
rectal temperature_mode: 38.0

pulse_mean: 71.91304347826087
pulse_median: 64.0
pulse_mode: 48.0

respiratory rate_mean: 30.417355371900825
respiratory rate_median: 24.5
respiratory rate_mode: 20.0

Количество пропущенных знацений в %%:

surgery?                       0.33
Age                            0.00
rectal temperature            20.00
pulse                          8.00
respiratory rate              19.33
temperature of extremities    18.67
pain                          18.33
outcome                        0.33
dtype: float64

In [9]:
# так как по базовым статистикам "rectal temperature" показатели отличаются не сильно предлагается 
# заполнить их значением "rectal temperature_mode".
# по столбцу "pulse" там где нет значений , предлагается убрать строки , т.к в них 
# как правило не хватает еще одного- двух значений, либо значение сильно уходит в выброс
# по столбцу "surgery?" так как там одно пропущенное значение и чаще всего встречается значение 1 , поставим именно его 

q1 = horse_df['pulse'].quantile(0.25)
q3 = horse_df['pulse'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
horse_df = horse_df[horse_df['pulse'].between(lower_bound, upper_bound, inclusive=True)]

horse_df['rectal temperature'] = horse_df['rectal temperature'].fillna(horse_df['rectal temperature'].mode()[0])
horse_df['surgery?'] = horse_df['surgery?'].fillna(1.0)
horse_df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app

,surgery?,Age,rectal temperature,pulse,respiratory rate,temperature of extremities,pain,outcome
0,2.0,1,38.5,66.0,28.0,3.0,5.0,2.0
1,1.0,1,39.2,88.0,20.0,NaN,3.0,3.0
2,2.0,1,38.3,40.0,24.0,1.0,3.0,1.0
4,2.0,1,37.3,104.0,35.0,NaN,NaN,2.0
6,1.0,1,37.9,48.0,16.0,1.0,3.0,1.0
...,...,...,...,...,...,...,...,...
295,1.0,1,38.0,120.0,70.0,4.0,2.0,3.0
296,2.0,1,37.2,72.0,24.0,3.0,4.0,3.0
297,1.0,1,37.5,72.0,30.0,4.0,4.0,2.0
298,1.0,1,36.5,100.0,24.0,3.0,3.0,1.0
299,1.0,1,37.2,40.0,20.0,NaN,NaN,3.0

In [10]:
# по уcловиям описания в колонке "Age" может быть только значения 1 либо 2 , 
# так как там значение 2 не присутствует вовсе , но есть значение 9 которого там быть 
# не должно, заменим 9 на 2
horse_df['Age'].where(~(horse_df.Age == 9), other=2, inplace=True)

In [14]:
# Так как по описанию значения в колонке "respiratory rate" могут сильно колебаться 
# а их полезность сомнительна - заполним пустые значения на 'no_info'
# так же заменим на 'no_info', значения в столбце 'temperature of extremities',
# хотя в описании написано , что этот показатель должен коррелироваться с повышенной 
# ректальной температурой , тем не мене данные в нашей выборке это не подтверждают ,
# поэтому чтобы не испортить уже имеющиеся данные поставим 'no_info'
# ну и с оставшимися параметрами "pain" и "outcome",  так как они не поддаются
# зависимости поставим 'no_info'

horse_df['respiratory rate'] = horse_df['respiratory rate'].fillna('no_info')
horse_df['temperature of extremities'] = horse_df['temperature of extremities'].fillna('no_info')
horse_df['pain'] = horse_df['pain'].fillna('no_info')
horse_df['outcome'] = horse_df['outcome'].fillna('no_info')

print('Количество пропущенных знацений в %%:')
(horse_df.isna().mean()*100).round(2)

Количество пропущенных знацений в %%:

surgery?                      0.0
Age                           0.0
rectal temperature            0.0
pulse                         0.0
respiratory rate              0.0
temperature of extremities    0.0
pain                          0.0
outcome                       0.0
dtype: float64